// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/cnc-csku/task-nexus/go-lib/grpcclient"
	"github.com/cnc-csku/task-nexus/task-management/config"
	"github.com/cnc-csku/task-nexus/task-management/domain/services"
	grpcclient2 "github.com/cnc-csku/task-nexus/task-management/internal/adapters/repositories/grpcclient"
	"github.com/cnc-csku/task-nexus/task-management/internal/adapters/repositories/mongo"
	"github.com/cnc-csku/task-nexus/task-management/internal/adapters/rest"
	"github.com/cnc-csku/task-nexus/task-management/internal/infrastructure/api"
	"github.com/cnc-csku/task-nexus/task-management/internal/infrastructure/database"
	"github.com/cnc-csku/task-nexus/task-management/internal/infrastructure/router"
	"github.com/cnc-csku/task-nexus/task-management/middlewares"
)

// Injectors from wire.go:

func InitializeApp() *api.EchoAPI {
	context := NewCtx()
	configConfig := config.NewConfig()
	client := database.NewMongoClient(configConfig, context)
	authMiddleware := middlewares.NewAdminJWTMiddleware(configConfig)
	healthCheckHandler := rest.NewHealthCheckHandler()
	grpcClientConfig := config.ProvideGrpcClientConfig(configConfig)
	grpcClient := grpcclient.NewGrpcClient(grpcClientConfig)
	grpcclientGrpcClient := grpcclient2.NewGrpcClient(context, grpcClient)
	commonService := services.NewCommonService(grpcclientGrpcClient)
	commonHandler := rest.NewCommonHandler(commonService)
	userRepository := mongo.NewMongoUserRepo(configConfig, client)
	userService := services.NewUserService(userRepository, configConfig)
	userHandler := rest.NewUserHandler(userService)
	projectRepository := mongo.NewMongoProjectRepo(configConfig, client)
	projectService := services.NewProjectService(userRepository, projectRepository, configConfig)
	projectHandler := rest.NewProjectHandler(projectService)
	routerRouter := router.NewRouter(authMiddleware, healthCheckHandler, commonHandler, userHandler, projectHandler)
	echoAPI := api.NewEchoAPI(context, configConfig, client, routerRouter)
	return echoAPI
}
