// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/cnc-csku/task-nexus/config"
	"github.com/cnc-csku/task-nexus/internal/adapters/rest"
	"github.com/cnc-csku/task-nexus/internal/infrastructure/api"
	"github.com/cnc-csku/task-nexus/internal/infrastructure/database"
	"github.com/cnc-csku/task-nexus/internal/infrastructure/router"
)

// Injectors from wire.go:

func InitializeApp() *api.EchoAPI {
	context := NewCtx()
	configConfig := config.NewConfig()
	client := database.NewMongoClient(configConfig, context)
	healthCheckHandler := rest.NewHealthCheckHandler()
	routerRouter := router.NewRouter(healthCheckHandler)
	echoAPI := api.NewEchoAPI(context, configConfig, client, routerRouter)
	return echoAPI
}
