// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/cnc-csku/task-nexus/go-lib/grpcclient"
	"github.com/cnc-csku/task-nexus/notification/config"
	"github.com/cnc-csku/task-nexus/notification/domain/services"
	"github.com/cnc-csku/task-nexus/notification/internal/infrastructure/api"
)

// Injectors from wire.go:

func InitializeGrpcServer() *api.GrpcServer {
	context := NewCtx()
	configConfig := config.NewConfig()
	grpcClientConfig := config.ProvideGrpcClientConfig(configConfig)
	grpcClient := core_grpcclient.NewGrpcClient(grpcClientConfig)
	notificationService := services.NewNotificationService(grpcClient)
	grpcServer := api.NewGrpcServer(context, configConfig, notificationService)
	return grpcServer
}
